name: 'Pytest Coverage Commentator'
description: 'A Github action to comments a Pytest Coverage on PR.'
author: 'Kuncoro Wicaksono'
branding:
  icon: 'message-circle'  
  color: 'yellow'
inputs:
  pytest-coverage:
    description: 'Where to find the txt output of pytest-coverage'
    required: true
    default: 'pytest-coverage.txt'
  token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
